# Generated by Django 3.2.12 on 2022-02-19 15:47

from django.db import migrations, models
import django.db.models.deletion
import shop.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(help_text='Enter a category (e.g. Phone)', max_length=200)),
                ('catid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['catid'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product image name', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.image_file)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the product name', max_length=200)),
                ('inventory', models.IntegerField(default='0')),
                ('price', models.IntegerField()),
                ('description', models.TextField(help_text='Enter a brief descripetion of the product', max_length=1000)),
                ('catid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.image')),
            ],
            options={
                'ordering': ['catid', 'pid'],
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('piid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this product', primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
    ]
