# Generated by Django 3.2.12 on 2022-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_image_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('digest', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('productList', models.JSONField()),
            ],
        ),
    ]
