# Generated by Django 3.2.12 on 2022-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
